name: JoinDate
version: ${project.version}
main: com.seailz.joindate.JoinDate
api-version: 1.18
authors: [ Seailz ]
description: Retrieve the first and last time a player joined the server
website: www.seailz.com
